PriceIt/PriceIt/Controllers/UserListController.cs
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Core.Mapping;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PriceIt.Data.Interfaces;
using System.Threading.Tasks;
using PriceIt.Data.Models;
using PriceIt.Models;

namespace PriceIt.Controllers
{
    public class UserListController : Controller
    {
        private readonly IListRepository _listRepository;
        private readonly IProductsRepository _productsRepository;

        public UserListController(IListRepository listRepository,IProductsRepository productsRepository)
        {
            _listRepository = listRepository;
            _productsRepository = productsRepository;
        }

        [Authorize]
        public IActionResult Index()
        {
            var user = _listRepository.GetCurrentUser();
            var lists = _listRepository.GetUserLists(user);

            return View(lists);
        }

        [Authorize]
        public IActionResult Add()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(string listname)
        {
            if (listname == null)
            {
                listname = "";
            }

            await _listRepository.AddListAsync(listname);

            if (!_listRepository.Save())
            {
                ViewData["SavingError"] = "error while saving";

                return View();
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            if (!_listRepository.HasAccessList(id))
            {
                return NotFound();
            }

            var list = _listRepository.GetUserListById(id);
            if (list == null)
                return NotFound();

            return View(list);
        }

        [Authorize]
        [HttpPost]
        public IActionResult DeletePost(int id)
        {
            if (!_listRepository.DeleteList(id))
                return BadRequest("Could not delete!");

            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            if (!_listRepository.HasAccessList(id))
            {
                return NotFound();
            }

            var list = _listRepository.GetUserListById(id);
            if (list == null)
                return NotFound();

            return View(list);
        }

        [Authorize]
        [HttpPost]
        public IActionResult EditPost(int id,string listname)
        {
            var list = _listRepository.GetUserListById(id);
            if (list == null)
                return NotFound();

            if(listname == null)
                list.Name = "";

            list.Name = listname;

            if (!_listRepository.UpdateList(list))
                return BadRequest("Could not edit");

            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Details(int id)
        {
            if (!_listRepository.HasAccessList(id))
                return NotFound();

            var list = _listRepository.GetUserListById(id);

            foreach (var listItem in list.ListItems)
            {
                listItem.Product = _productsRepository.GetProduct(listItem.ProductId);
            }

            return View(list);
        }

        [Authorize]
        public IActionResult DetailsWithSimilarProducts(int productId)
        {
            if (productId < 1)
                return NotFound();

            var product = _productsRepository.GetProduct(productId);

            if (product == null)
                return NotFound();

            var similarProducts =
                _productsRepository.Search(product.Name, product.Category);

            similarProducts.Remove(product);

            var viewModel = new DetailsWithSimilarProductsViewModel()
            {
                Product = product,
                SimilarProducts = similarProducts ?? new List<Product>() 
            };

            return View(viewModel);
        }

        [Authorize]
        public IActionResult AddProductToList(int productId)
        {
            var user = _listRepository.GetCurrentUser();
            var lists = _listRepository.GetUserLists(user);

            if (lists == null || !lists.Any())
            {
                return RedirectToAction("Index");
            }

            var viewModel = new AddProductToListViewModel
            {
                ProductId = productId,
                Lists = lists
            };

            return View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddProductToListPost(int productId, int listId)
        {
            var list = _listRepository.GetUserListById(listId);

            if (list == null)
                return NotFound();

            var product = _productsRepository.GetProduct(productId);

            if (product == null)
                return NotFound();

            if (!_listRepository.AddProductToList(product, list)) return BadRequest("Could not save!");
            
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public IActionResult IncreaseListItemCount(int listId, int itemId)
        {
            var list = _listRepository.GetUserListById(listId);

            if (list == null)
                return NotFound();

            if (!_listRepository.IncreaseListItemCount(list, itemId))
                return BadRequest("Failed to increase product quantity please try again");

            return RedirectToAction("Details", new { id = listId});
        }

        [Authorize]
        [HttpPost]
        public IActionResult DecreaseListItemOrDelete(int listId, int itemId)
        {
            var list = _listRepository.GetUserListById(listId);

            if (list == null)
                return NotFound();

            if (!_listRepository.DecreaseListItemOrDelete(list, itemId))
                return BadRequest("Failed to decrease product quantity please try again");

            return RedirectToAction("Details", new {id = listId});
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PriceIt/PriceIt/Views/Shared/UserList/_ProductPreviewPartial.cshtml
@using PriceIt.Data.Models
@model PriceIt.Data.Models.Product

@{
    var productLink = "";

    @if (Model.Website == Website.Amazon)
    {
        productLink = "https://www.amazon.de" + Model.ProductUrl;
    }

    @if (Model.Website == Website.MediaMarkt)
    {
        productLink = "https://www.mediamarkt.de" + Model.ProductUrl;
    }

    @if (Model.Website == Website.Saturn)
    {
        productLink = "https://www.saturn.de" + Model.ProductUrl;
    }
}

<div class="container">

    <a href="@productLink">
        <h5>@Model.Name</h5>
        <img src="@Model.ProductImageUrl" alt="@Model.Name" />
    </a>
    
    <p>Last updated at: @Model.LastUpdate</p>

    <p>price : @Model.Price</p>
        
    <a class="btn btn-outline-primary" asp-controller="UserList" asp-action="DetailsWithSimilarProducts" asp-route-productId="@Model.Id">Check Similar Products</a>
    <a class="btn btn-light" asp-controller="UserList" asp-action="AddProductToList" asp-route-productId="@Model.Id">Added to a list</a>
</div>

PriceIt/PriceIt/Views/Shared/UserList/_UserListItemPartial.cshtml
@using PriceIt.Data.Models
@model PriceIt.Data.Models.ListItem

@{
    var productLink = "";

    @if (Model.Product.Website == Website.Amazon)
    {
        productLink = "https://www.amazon.de" + Model.Product.ProductUrl;
    }

    @if (Model.Product.Website == Website.MediaMarkt)
    {
        productLink = "https://www.mediamarkt.de" + Model.Product.ProductUrl;
    }

    @if (Model.Product.Website == Website.Saturn)
    {
        productLink = "https://www.saturn.de" + Model.Product.ProductUrl;
    }
}

@if (Model.Product != null)
{
<div class="container">
    <a href="@productLink">
        <h5>@Model.Product.Name</h5>
        <img src="@Model.Product.ProductImageUrl" alt="@Model.Product.Name" />
    </a>
    <p>price : @Model.Product.Price</p>

    <p>Quantity : @Model.Quantity</p>

    <div>
        <form asp-controller="UserList" asp-action="IncreaseListItemCount">
            <input type="hidden" name="listId" value="@Model.UserListId" />
            <input type="hidden" name="itemId" value="@Model.ListItemId" />
            <input type="submit" value="Add" />
        </form>

        <form asp-controller="UserList" asp-action="DecreaseListItemOrDelete">
            <input type="hidden" name="listId" value="@Model.UserListId" />
            <input type="hidden" name="itemId" value="@Model.ListItemId" />
            <input type="submit" value="Remove" />
        </form>
    </div>
</div>
}

PriceIt/PriceIt/Views/Shared/UserList/_UserListPartial.cshtml
@model PriceIt.Data.Models.UserList

<div class="container">
    <a asp-controller="UserList" asp-action="Details" asp-route-id="@Model.UserListId">@Model.Name</a>
    
    <divs>
        <div>
            <a class="btn btn-outline-primary" asp-controller="UserList" asp-action="Details" asp-route-id="@Model.UserListId">Details</a>
            <a class="btn btn-outline-primary" asp-controller="UserList" asp-action="Edit" asp-route-id="@Model.UserListId">Edit</a>
            <a class="btn btn-outline-danger" asp-controller="UserList" asp-action="Delete" asp-route-id="@Model.UserListId">Delete</a>
        </div>
    </divs>

</div>